/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kido.hotel.main;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.*;

/**
 *
 * @author marqm
 */
public class MainBody extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel contentPanel;

    /**
     * Creates new form GuestSupplies
     */
    public MainBody() {

        initComponents();
        setupCardLayout(); // Configura CardLayout correctamente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMItems = new javax.swing.JMenu();
        jMUser = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guest Supplies Register");

        jMenu3.setText("Registry");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMItems.setText("Items");
        jMItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMItemsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMItems);

        jMUser.setText("Users");
        jMUser.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMUserMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMUserMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMUser);

        jMenu4.setText("Logout");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMUserMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMUserMenuKeyPressed

    }//GEN-LAST:event_jMUserMenuKeyPressed

    private void jMUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMUserMouseClicked
        showPanel("Users");

    }//GEN-LAST:event_jMUserMouseClicked

    private void jMItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMItemsMouseClicked
        
    }//GEN-LAST:event_jMItemsMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        showPanel("Supplies");
    }//GEN-LAST:event_jMenu3MouseClicked
    private void setupCardLayout() {
        
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        // Agregamos los paneles reutilizando el método
        addPanelToCardLayout(new JPanel(), "Home");
        addPanelToCardLayout(new Supplies(), "Supplies");
        addPanelToCardLayout(new Users(), "Users");

        setContentPane(contentPanel);
        showPanel("Supplies");
    }

    private void addPanelToCardLayout(JPanel panel, String name) {
        contentPanel.add(panel, name);
    }

    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new MainBody().setVisible(true));
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) { // Usa el estilo de Windows
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMItems;
    private javax.swing.JMenu jMUser;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
