/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kido.hotel.main;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.*;

/**
 *
 * @author marqm
 */
public class MainBody extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel contentPanel;
    private Supplies suppliesPanel; // Guardamos la instancia

    /**
     * Creates new form GuestSupplies
     */
    public MainBody() {

        initComponents();
        setupCardLayout(); // Configura CardLayout correctamente
    }

   private void setupCardLayout() {
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        suppliesPanel = new Supplies(); // Instancia única

        contentPanel.add(new JPanel(), "Home");
        contentPanel.add(suppliesPanel, "Supplies");

        setContentPane(contentPanel); // Evita elementos duplicados
        showPanel("Supplies");
        revalidate();
        repaint();
    }

    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guest Supplies Register");

        jMenu3.setText("Registry");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Items");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Users");
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Logout");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new MainBody().setVisible(true));
        try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) { // Usa el estilo de Windows
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    e.printStackTrace();
}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
